services:
  db:
    image: postgres:17
    container_name: scrapp-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
