basePath: /
definitions:
  controllers.UserResponse:
    properties:
      id:
        example: 1
        type: integer
      message:
        example: User created successfully
        type: string
      name:
        example: Rajan
        type: string
    type: object
  main.PingResponse:
    properties:
      message:
        type: string
    type: object
  main.UserScrappResponse:
    properties:
      message:
        type: string
      userId:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      phone:
        type: string
    type: object
host: localhost:8090
info:
  contact: {}
  description: This is the backend API for Scrapp application built with Gin
  title: Scrapp Backend API
  version: "1.0"
paths:
  /api/users/signup:
    post:
      consumes:
      - application/json
      description: Creates a new user in the system
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new user
      tags:
      - users
  /ping:
    get:
      description: Returns pong to verify the API is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PingResponse'
      summary: Health check endpoint
      tags:
      - health
  /scrapp/{userId}:
    get:
      description: Retrieves scrapp data for a specific user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.UserScrappResponse'
      summary: Get user scrapp data
      tags:
      - scrapp
swagger: "2.0"
